### ISSUE TITLE
Broken Link: CONTRIBUTE.md

### ISSUE THREAD

**Issue by brianberlin** [mxstbr/react-boilerplate-site#10]
The link at the bottom of the page for `Start Contributing` is broken. I found it in the git issue cue but I think it must have been overwritten at some point. 

https://github.com/mxstbr/react-boilerplate/commit/cafd823b9208e4f1a863f61302a380348fc24509

**Comment by brotzky** [comment]
Thanks has been fixed: https://github.com/mxstbr/react-boilerplate-site/pull/13
thanks for the report.
